---
name: geo_job_artifact_replication
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/issues/327400
rollout_issue_url:
milestone: '14.8'
type: development
group: group::geo
default_enabled: false
