#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <gem-name>"
  exit 1
fi

if ! gem specification --remote --ruby "$1"; then
  echo "The '$1' is missing. Push stub gem to RubyGems with version 0.0.1."
  exit 1
fi
