templates-shellcheck:
  extends:
    - .ci-templates:rules:shellcheck
    - .default-before_script
    - .default-retry
    - .ruby-cache
    - .use-pg15
  stage: test
  needs:
    - setup-test-env
  script:
    # Try bullseye (0.7) first and then bookworm (0.9)
    - apt update && apt install -y shellcheck=0.7.1-1+deb11u1 || apt install -y shellcheck=0.9.0-1
    - bundle exec scripts/lint_templates_bash.rb
